#pragma config(Sensor, in1,    mobilePot,      sensorPotentiometer)
#pragma config(Sensor, in2,    liftRightPot,   sensorPotentiometer)
#pragma config(Sensor, in3,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    liftLeftPot,    sensorPotentiometer)
#pragma config(Sensor, in5,    driveGyro,      sensorGyro)
#pragma config(Sensor, dgtl1,  rightDriveEnc,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDriveEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rollerEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  MOSI,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  SCLK,           sensorDigitalOut)
#pragma config(Motor,  port1,           mobileGoal,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveBL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveBR,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port4,           driveFL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveFR,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           swingingArm,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           roller,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           liftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Declare VEX as the robot platform

#pragma platform(VEX)

// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

// **** Important programmer notes ****
//
// When upgrading ROBOTC the Robot Platform Settings are lost and must be reset
// otherwise compiler error will result. Ensure the following are set:
// 		Robot -> Platform Type -> VEX 2.0 Cortex
// 		Robot -> Platform Type -> VEX Robotics -> VEX 2.0 Cortex
// 		Robot -> Platform Type -> Natural Language (PLTW)
//
//
// Note: Sometime when upgrading FW on the controller and/or joystick, the FW for the
//       VEXNet Keys must also be upgraded. The symptom of needing this upgrade is a
//       failure of the controller and joystick to communicate with each other.
//
//
// Note: When RobotC refuses to download code to the robot, first try manually selecting the
//       COM port. If that doesn't work then it may be necessary reload the firmware. First
//       update the main FW and then the RobotC FW. Don't forget to rename robot afterwards.
//
//
// Variable info:
//
//		int, short, word - 2 bytes
//		long - 4 bytes
//		SensorValue() returns 2 byte value

// Control debugger windows by defining these pragmas
#pragma DebuggerWindows("debugStream")

#include "Team8800Lib.c"		// Utility routines to simplify programming
#include "Team8800Led.c"		// Routines to control the LED strip
#include "MultiTask.c"  // Motor slew control

// Delcarations

int number = 10;

// Initialize
void initialize();
void initializeGyro();
void selectTeamAlliance();

// Controller Input
//void processController();

// Autonomous
//void autonomousRoutines();

// Robot Action

//Functions
void moveLiftDown(int speed, int distance);
void moveArmOut();
void moveArmIn();
void moveArmOutAuto();
void moveArm(bool forward);
void moveLiftUp(int speed, int distance);
void moveLiftUpAuto(int speed, int distance);
void rollerIntake(int speed);
void rollerOutake(int speed, int time);

void liftPIDCalculate (int position);
void liftPIDControl(int position);
void checkLiftPos (int height);
void autoDrivePIDCalculate (int distance);
void autoDrivePIDControl (int distance, bool time);
void autoGyroPIDCalculate (int setAngle);
void autoGyroPIDControl (int setAngle);
void autoDriveGyroPIDCalculate (int setAngle, int distance);
void autoDriveGyroPIDControl (int setAngle, int distance);
void autoLiftPIDControl (int position, int kp, int ki, int kd);

//Auto Functions
void moveMobileGoalOutAndDrive(int speed, int distance);
void moveMobileGoalInAndDrive(int speed, int distance);
void autoLiftControl (int height);
void drive(int left, int right);
void driveForward(int speed, int distance);
void driveBackward(int speed, int distance);
void turnLeft(int speed, int distance);
void turnRight(int speed, int distance);
void clearDriveEnc();
void moveMobileGoalOutAuto();
void moveMobileGoalInAuto();
void moveMobileGoalOut();
void moveMobileGoalIn();
void moveMobileGoalInDistance(int distance);
void rollerOutakeAuto(int speed, int distance);
void collectMobileGoal();
void intakeMobileGoalAndStackFirstCone();
void stackSecondConeAndCollectThirdCone();

void autoStackStep(int liftPos);

void autoStack (int level);
void postStacking();

// Constants and global vars
const byte MIN_JOYSTICK_THRESHOLD = 30;

const byte RED_ALLIANCE = 1;
const byte BLUE_ALLIANCE = 2;
byte allianceColor = BLUE_ALLIANCE;

const byte LEFT = 1;
const byte RIGHT = 2;
byte allianceSide = RIGHT;

const byte AUTONOMOUS_MODE_MOBILE_GOAL_20 = 1;
const byte AUTONOMOUS_MODE_STATIONARY = 2;
const byte AUTONOMOUS_MODE_4_20 = 3;
const byte AUTONOMOUS_MODE_SKILLS = 4;
const byte AUTONOMOUS_MODE_3_10 = 5;
const byte AUTONOMOUS_MODE_STACK_PIPE = 6;
const byte AUTONOMOUS_MODE_STACK_BACK = 7;
const byte AUTONOMOUS_MODE_DRIVE_BLOCK = 8;
byte autonomousMode = AUTONOMOUS_MODE_MOBILE_GOAL_20;

const byte PRESET_LEVEL_ONE = 1;
const byte PRESET_LEVEL_TWO = 2;
const byte PRESET_LEVEL_THREE = 3;
const byte PRESET_LEVEL_FOUR = 4;
const byte PRESET_LEVEL_FIVE = 5;
const byte PRESET_LEVEL_SIX = 6;
const byte PRESET_LEVEL_SEVEN = 7;
const byte PRESET_LEVEL_EIGHT = 8;
const byte PRESET_LEVEL_NINE = 9;
const byte PRESET_LEVEL_TEN = 10;
const byte PRESET_LEVEL_ELEVEN = 11;
const byte PRESET_LEVEL_TWELVE = 12;
const byte PRESET_LEVEL_THIRTEEN = 13;
const byte PRESET_LEVEL_FOURTEEN = 14;
const byte PRESET_LEVEL_FIFTEEN = 15;
byte presetLevel = PRESET_LEVEL_ONE;

unsigned long autonomousStartTime;

const byte AUTONOMOUS = 1;
const byte USER_CONTROL = 2;
byte robotMode = 1;

bool presetLevelActive = false;
bool presetLevelJustActive = false;

bool boingyPointOn = true;
bool armBack = false;
bool armFront = true;

bool stacking = false;
bool stackPrev = false;
bool justStacked = false;

bool increaseStackLvl;

bool armIsBack = false;
bool armIsReallyBack;
bool armIsBackLvl1and2;
bool armIsForward;
bool liftLeftIsPosition4;
bool liftRightIsPosition4 = false;
bool liftIsPosition4Again = false;
bool liftIsPosition5;
bool liftIsPosition6;
bool liftIsDown = false;

bool liftLeftAtPosition;
bool liftRightAtPosition;
bool driveAtPosition;
bool turnAtPosition;

bool mobileGoalOut;

bool rollerIntaking = false;
bool outakeFinished = false;

bool btnSixUPressed = false;
bool btnSixDPressed = false;

bool presetLevelScrollUp = false;
bool presetLevelScrollDown = false;

bool timeUp = false;

bool mobileGoalIsOut;

int h1 = 480;
int h2 = 560;
int h3 = 680;
int h4 = 840;
int h5 = 1000;
int h6 = 1080;
int h7 = 1140;
int h8 = 1310;
int h9 = 1460;
int h10 = 1550;
int h11 = 1750;
int h12 = 1970;
int h13 = 2020;
int h14 = 2040;

int autoStackExraHeight = 100;
int autoStackOutTime = 450;
int autoStackDownTime = 300;


int armPower;

int stackLevel = 1;
int prevStackLevel = 0;

int liftLeftPositionError = 65;
int liftRightPositionError = 65;
int drivePositionError = 1;
int turnPositionError = 1;
int turnDrivePositionError = 2;
int driveTurnPositionError = 200;
int armError = 2;

//Lift PID values
float liftkp = 0.63;
float liftki = 0.04;
float liftkd = -0.05;

//Drive PID values
float drivekp = 0.25;
float driveki = 0.0036;
float drivekd = 0.06;

//Turn PID values
float turnkp = 0.6;
float turnki = 0.000003;
float turnkd = 0.1;

//Turn Drive PID values
float turnDrivekp;
float turnDriveki;
float turnDrivekd;

//Drive Turn PID values
float driveTurnkp = 0.65;
float driveTurnki;
float driveTurnkd;

float turnError;

int driveCurrent;
int gyroCurrent;
int overallCurrentLeft;
int overallCurrentRight;

int maxTurnPower = 15;

int rollerSpeed;

void pre_auton()
{
	bStopTasksBetweenModes = true;

	clearDebugStream();
	writeDebugStreamLine("Pre-Autonomous...");

	initializeGyro();

	// Select alliance using LCD and indicate selection with LEDs
	selectTeamAlliance();
}

task autonomousRoutines()
{
	switch (autonomousMode) {
	case AUTONOMOUS_MODE_MOBILE_GOAL_20:
		//////////////////////////////////////////////////////////////Mobile Goal 20////////////////////////
		motor[roller] = 40;

		clearTimer(T2);

		while (time1(T2) < 3000) {

			moveLiftUp(100, 700);

			//Drive
			if (time1(T2) > 500) {
				//autoDriveGyroPIDControl(0, 1350, 1, 0.00015, 0.5, 0.00002, 0.000000000079, 1.3);
			}

			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
				} else {
				motor[mobileGoal] = -50;
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 2300) {

			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 50;
			}

			//Drive
			if (time1(T2) > 1600) {
				driveBackward(-100, -460);
				moveLiftDown(50, 400);
				//autoDriveGyroPIDControl(0, -1200, 1, 0.00015, 1.0, 1, 0.0000002, 0.4);
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		wait1Msec(200);

		if (allianceSide == RIGHT) {
			while (time1(T2) < 1000) {
				//turn
				autoGyroPIDControl(-300);
			}
			} else if (allianceSide == LEFT) {
			while (time1(T2) < 1000) {
				//turn
				autoGyroPIDControl(300);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 1000) {
			//drive backward
			driveBackward(-100, -60);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();
		if (allianceSide == RIGHT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(-1500);
			}
			} else if (allianceSide == LEFT) {
			while (time1(T2) < 1000) {
				//turn
				autoGyroPIDControl(1500);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();
		SensorValue[rollerEnc] = 0;

		while (time1(T2) < 2000) {
			moveMobileGoalOut();

			moveLiftUp(100, 500);

			rollerOutake(-100, 150);

			if (time1(T2) > 300) {
				drive(100, 100);
				wait1Msec(600);
				drive(0, 0);
			}
			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 600) {
			drive(-60, -60);
			waitInMilliseconds(400);
			drive(0, 0);
		}
		moveMobileGoalInAuto();


		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		///////////////////////////////////////////////////////////////////////End Mobile Goal 20//////////////////////////
		break;

	case AUTONOMOUS_MODE_STATIONARY:

		/////////////////////////////////////////////////////////////////////////////AUTO 2///////////////////////////////////////////
		//Apply passive power to roller

		motor [roller] = 40;

		clearTimer(T2);

		//move lift up
		while (time1(T2) < 1000) {
			if (time1(T2) < 1000) {
				moveLiftUp(70, 800);
				} else {
				motor[liftL] = 0;
				motor[liftL] = 0;
			}
		}

		waitInMilliseconds(300);

		//drive forward
		driveForward(60, 200);

		waitInMilliseconds(100);

		//move swinging arm out
		moveArmOutAuto();

		waitInMilliseconds(200);

		moveArmIn();
		motor[roller] = -127;

		waitInMilliseconds(200);

		if (allianceSide == LEFT) {
			driveBackward(-100, -700);
			} else if (allianceSide == RIGHT) {
			driveBackward(-700, -100);
		}

		waitInMilliseconds(200);

		clearTimer(T2);

		while (time1(T2) < 600) {
			autoDrivePIDControl(-300, true);
		}
		waitInMilliseconds(100);

		driveForward(100, 3000);

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		//////////////////////////////////////////////////////End of auto 2/////////////////////////////////
		break;

	case AUTONOMOUS_MODE_4_20:

		////////////////////////////////////////////////////////////////////////////////AUTO 3/////////////////////////////////////////////////
		motor[roller] = 40;

		clearDriveEnc();
		clearTimer(T2);

		collectMobileGoal();

		waitInMilliseconds(100);

		clearDriveEnc();
		clearTimer(T2);

		intakeMobileGoalAndStackFirstCone();

		waitInMilliseconds(100);

		clearDriveEnc();
		clearTimer(T2);

		stackSecondConeAndCollectThirdCone();



		/*while (time1(T2) < 3000) {

			moveLiftUp(100, 700);

			//Drive
			if (time1(T2) > 500) {
				//autoDriveGyroPIDControl(0, 1350, 1, 0.00015, 0.5, 0.00002, 0.000000000079, 1.3);
			}

			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
				} else {
				motor[mobileGoal] = -50;
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 2200) {

			if (mobileGoalIsOut) {
				moveMobileGoalInAuto();
				} else {
				motor[mobileGoal] = 50;
			}

			if (time1(T2) > 1600) {
				moveLiftDown(50, 400);
				//autoDriveGyroPIDControl(0, -1200, 1, 0.00015, 1.0, 1, 0.0000002, 0.4);
			}

			if (time1(T2) > 2050) {
				rollerOutake(-100, 150);
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 1500) {
			//autoDriveGyroPIDControl(0, 200, 1, 0.00015, 0.5, 1, 0.000079, 0.000003);

			moveLiftDown(50, 300);

			moveArmOut();

			motor[roller] = 120;
			if (time1(T2) > 1000) {
				motor[roller] = 40;
				moveLiftUp(100, 550);
			}
			if (time1(T2) > 1300) {
				moveArmIn();
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();


		if (allianceSide == LEFT) {
			while (time1(T2) < 1000) {
				moveLiftDown(20, 550);
				driveBackward(-100, -580);
				if (time1(T2) > 200) {
					motor[roller] = -100;
					waitInMilliseconds(400);
					motor[roller] = 0;
				}
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 1000) {
				moveLiftDown(20, 550);
				driveBackward( -580, -100);
				if (time1(T2) > 200) {
					motor[roller] = -100;
					waitInMilliseconds(400);
					motor[roller] = 0;
				}
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		wait1Msec(200);

		if (allianceSide == LEFT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(-1700);
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(1700);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 1500) {
			moveMobileGoalOut();
			moveLiftUp(80, 500);
			motor[roller] = -100;

			drive(50, 50);
			waitInMilliseconds(200);
			drive(0, 0);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 300) {
			drive(-60, -60);
			waitInMilliseconds(200);
			drive(0, 0);
		}

		if (mobileGoalIsOut) {
			moveMobileGoalInAuto();
			} else {
			motor[mobileGoal] = 50;
		}*/

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		//////////////////////////////////////////////////////End of auto 3/////////////////////////////////////////////////////
		break;

	case AUTONOMOUS_MODE_SKILLS:
		//////////////////////////////////////////////////////////Auto 4/////////////////////////////////////

		motor[roller] = 40;

		clearTimer(T2);

		while (time1(T2) < 3000) {

			if (time1(T2) < 300) {
				moveLiftUp(100, 400);
				} else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}

			//Drive
			if (time1(T2) > 500 && time1(T2) < 700) {
				motorReq2[driveBL] = 90;
				motorReq2[driveBR] = 90;
				motorReq2[driveFL] = 90;
				motorReq2[driveFR] = 90;
			}
			//Drive
			if (time1(T2) > 700) {
				//autoDriveGyroPIDControl(0, 1300, 1, 0.00015, 0.5, 0.00002, 0.000000000079, 1.3);
			}

			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
				} else {
				motor[mobileGoal] = -50;
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		//Move Mobile goal in and start stacking second cone
		while (time1(T2) < 2200) {

			if (time1(T2) < 300) {
				moveLiftUp(100, 500);
				} else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}
			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 50;
			}

			if (time1(T2) > 1600 && time1(T2) < 2050) {
				moveLiftDown(50, 400);
				//autoDriveGyroPIDControl(0, -1200, 1, 0.00015, 1.0, 1, 0.0000002, 0.4);
			}

			if (time1(T2) > 2050) {
				moveLiftUp(80, 600);
				//autoDriveGyroPIDControl(0, -1200, 1, 0.00015, 1.0, 1, 0.0000002, 0.4);
			}

			if (time1(T2) > 2050) {
				rollerOutake(-100, 150);
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearDriveEnc();

		moveArmOut();
		motor[roller] = 120;

		while (time1(T2) < 1500) {
			//autoDriveGyroPIDControl(0, 300, 1, 0.00015, 0.5, 1, 0.000079, 0.000003);

			moveLiftDown(50, 300);

			if (time1(T2) > 1000) {
				motor[roller] = 40;
				moveLiftUp(100, 550);
			}
			if (time1(T2) > 1300) {
				moveArmIn();
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		if (allianceSide == LEFT) {
			while (time1(T2) < 1000) {
				moveLiftDown(20, 550);
				driveBackward(-580, -100);
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 1000) {
				moveLiftDown(20, 550);
				driveBackward(-100, -580);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		wait1Msec(200);

		if (allianceSide == LEFT) {
			while (time1(T2) < 1000) {
				//turn
				autoGyroPIDControl(300);
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 1000) {
				//turn
				autoGyroPIDControl(-300);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 1000) {
			//drive backward
			driveBackward(-100, -60);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		if (allianceSide == LEFT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(1400);
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(-1400);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();
		SensorValue[rollerEnc] = 0;

		while (time1(T2) < 2000) {
			moveMobileGoalOut();

			moveLiftUp(100, 500);

			rollerOutake(-100, 150);

			if (time1(T2) > 300) {
				drive(100, 100);
				wait1Msec(600);
				drive(0, 0);
			}
			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 600) {
			drive(-60, -60);
			waitInMilliseconds(400);
			drive(0, 0);
		}
		moveMobileGoalInAuto();

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		///////////////////////////////////////////////////////////////Auto 4 End///////////////////////////////////////////
		break;

	case AUTONOMOUS_MODE_3_10:
		/////////////////////////////////////////////////////////////////////////////AUTO 5////////////////////////////////
		motor[roller] = 40;

		clearTimer(T2);

		while (time1(T2) < 3000) {

			if (time1(T2) < 300) {
				moveLiftUp(100, 400);
				} else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}

			//Drive
			if (time1(T2) > 500 && time1(T2) < 700) {
				motorReq2[driveBL] = 90;
				motorReq2[driveBR] = 90;
				motorReq2[driveFL] = 90;
				motorReq2[driveFR] = 90;
			}
			//Drive
			if (time1(T2) > 700) {
				//autoDriveGyroPIDControl(0, 1300, 1, 0.00015, 0.5, 0.00002, 0.000000000079, 1.3);
			}

			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
				} else {
				motor[mobileGoal] = -50;
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		//Move Mobile goal in and start stacking second cone
		while (time1(T2) < 2200) {

			if (time1(T2) < 300) {
				moveLiftUp(100, 500);
				} else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}
			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 50;
			}

			if (time1(T2) > 1600 && time1(T2) < 2050) {
				moveLiftDown(50, 400);
				//autoDriveGyroPIDControl(0, -1200, 1, 0.00015, 1.0, 1, 0.0000002, 0.4);
			}

			if (time1(T2) > 2050) {
				moveLiftUp(80, 600);
				//autoDriveGyroPIDControl(0, -1200, 1, 0.00015, 1.0, 1, 0.0000002, 0.4);
			}

			if (time1(T2) > 2050) {
				rollerOutake(-100, 150);
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		//Start intaking second cone
		moveArmOut();
		motor[roller] = 120;

		while (time1(T2) < 1500) {
			//autoDriveGyroPIDControl(0, 260, 1, 0.00015, 0.5, 1, 0.000079, 0.000003);

			moveLiftDown(50, 300);

			if (time1(T2) > 1000) {
				motor[roller] = 40;
				moveLiftUp(100, 550);
			}
			if (time1(T2) > 1300) {
				moveArmIn();
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();
		SensorValue[rollerEnc] = 0;

		//Start stacking second cone
		while (time1(T2) < 1000) {
			if (time1(T2) < 750) {
				moveLiftDown(80, 400);
			}

			if (time1(T2) > 750) {
				moveLiftUp(80, 600);
			}

			if (time1(T2) > 750) {
				rollerOutake(-100, 150);
			}

			wait1Msec(20);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();


		//Start intaking third cone
		moveArmOut();
		motor[roller] = 127;

		while (time1(T2) < 1500) {
			//autoDriveGyroPIDControl(0, 230, 1, 0.00015, 0.5, 1, 0.000079, 0.000003);

			moveLiftDown(50, 300);

			if (time1(T2) > 1000) {
				motor[roller] = 40;
				moveLiftUp(100, 550);
			}
			if (time1(T2) > 1300) {
				moveArmIn();
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		while (time1(T2) < 1750) {
			moveLiftDown(20, 550);
			driveBackward(-100, -700);
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		wait1Msec(150);

		if (allianceSide == LEFT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(1850);
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 2000) {
				//turn
				autoGyroPIDControl(-1850);
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		if (allianceSide == LEFT) {
			while (time1(T2) < 1500) {
				moveMobileGoalOut();
				moveLiftUp(80, 500);
				motor[roller] = -100;

				if (time1(T2) < 1000) {
					drive(85, 45);
					} else {
					drive(0, 0);
				}
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 1500) {
				moveMobileGoalOut();
				moveLiftUp(80, 500);
				motor[roller] = -100;

				if (time1(T2) < 1000) {
					drive(45, 85);
					} else {
					drive(0, 0);
				}
			}
		}

		drive(0, 0);
		clearTimer(T2);
		clearDriveEnc();

		if (allianceSide == LEFT) {
			while (time1(T2) < 300) {
				drive(-127, -50);
				waitInMilliseconds(200);
				drive(0, 0);
			}
			} else if (allianceSide == RIGHT) {
			while (time1(T2) < 300) {
				drive(-50, -127);
				waitInMilliseconds(200);
				drive(0, 0);
			}
		}

		if (mobileGoalIsOut) {
			moveMobileGoalInAuto();
			} else {
			motor[mobileGoal] = 50;
		}

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		//////////////////////////////////////////////////////////Auto 5 end/////////////////////////////////////////////
		break;

	case AUTONOMOUS_MODE_STACK_PIPE:
		if (allianceSide == LEFT) {
			clearTimer(T2);
			while (time1(T2) < 800) {
				autoGyroPIDControl(-250);
			}

			clearTimer(T2);
			drive(0, 0);

			while (time1(T2) < 2400) {
				drive(127, 127);
			}

			drive(0, 0);

			} else if (allianceSide == RIGHT) {
			clearTimer(T2);
			while (time1(T2) < 800) {
				autoGyroPIDControl(250);
			}

			clearTimer(T2);
			drive(0, 0);

			while (time1(T2) < 2400) {
				drive(127, 127);
			}

			drive(0, 0);
		}

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		break;

	case AUTONOMOUS_MODE_STACK_BACK:
		clearDriveEnc();
		//clearTimer(T2);
		while(true) {
			autoGyroPIDControl(940);
			writeDebugStreamLine("Turn Value gyro %d", SensorValue[driveGyro]);

		}

		/*clearDriveEnc();

		while (true) {
			autoDriveGyroPIDControl(0, -2000);
		}*/
		break;

	case AUTONOMOUS_MODE_DRIVE_BLOCK:

		break;
	}
}

task autonomous()
{
	robotMode = AUTONOMOUS;

	autonomousStartTime = nSysTime;
	writeDebugStreamLine("Starting Autonomous...");

	initialize();

	if (false) AutonomousCodePlaceholderForTesting();  // complains if I remove this

	startTask(autonomousRoutines);
}

task ProcessController() {
	while(true) {

		/*
		Main Controller:
		joysticks = drive
		8U mobile goal full out
		8D mobile goal full in
		8L mobile goal partial in
		8R mobile goal partial out

		Partner Contorller:
		5U lift up
		5D lift down
		6D roller out
		6U roller in
		7U
		7D stop auto stacking and reset to level 1
		7L lift at mobile goal height
		7R
		8U acivate current level
		8D activate last level
		8L arm out
		8R arm in

		*/

		// --- Joysticks to control robot driving (main controller only)

		static byte rightJoystickY, leftJoystickY, prevRightJoystickY = 0, prevLeftJoystickY = 0;

		rightJoystickY = readRightJoystickYAxis();
		leftJoystickY = readLeftJoystickYAxis();

		static bool rightDriveMoving = false;
		if (abs(rightJoystickY) > MIN_JOYSTICK_THRESHOLD) {
			rightDriveMoving = true;
			motorReq2[driveFR] = rightJoystickY;
			motorReq2[driveBR] = rightJoystickY;
			writeDebugStreamLine("Right: %d%%", rightJoystickY);
			} else {
			rightDriveMoving = false;
			motorReq2[driveFR] = 0;
			motorReq2[driveBR] = 0;
		}

		static bool leftDriveMoving = false;
		if (abs(leftJoystickY) > MIN_JOYSTICK_THRESHOLD) {
			leftDriveMoving = true;
			motorReq2[driveFL] = leftJoystickY;
			motorReq2[driveBL] = leftJoystickY;
			writeDebugStreamLine("Left: %d%%", leftJoystickY);
			} else {
			leftDriveMoving = false;
			motorReq2[driveFL] = 0;
			motorReq2[driveBL] = 0;
		}

		if (!stacking) {
			if (isButtonPressed(Btn8RXmtr2)) {
				armIsBack = true;
				} else if (isButtonPressed(Btn8LXmtr2)) {
				armIsBack = false;
			}

			if (armIsBack) {
				moveArmOut();
				} else if (!armIsBack) {
				moveArmIn();
			}
		}

		//Mobile Goal control on joystick
		if (isButtonPressed(Btn8U)) {
			mobileGoalOut = true;
			} else if (isButtonPressed(Btn8D)) {
			mobileGoalOut = false;
		}

		if (isButtonPressed(Btn8R)) {
			moveMobileGoalOut();
			} else if (isButtonPressed(Btn8L)) {
			moveMobileGoalIn();
			} else if (mobileGoalOut) {
			moveMobileGoalOut();
			} else if (!mobileGoalOut) {
			moveMobileGoalIn();
		}

		//Roller control
		if (!stacking) {
			if (isButtonPressed(Btn6DXmtr2)) {
				motor[roller] = -127;
				} else if (isButtonPressed(Btn6UXmtr2)) {
				motor[roller] = 127;
				} else {
				motor[roller] = 25;
				//motor[roller] = 0;
			}
		}

		//Move lift
		if (!stacking) {
			if (isButtonPressed(Btn5UXmtr2)) {
				motor[liftL] = 127;
				motor[liftR] = 127;
				//liftPIDControl(1000);
				stacking = false;
				justStacked = false;
				stackPrev = false;
			} else if (isButtonPressed(Btn5DXmtr2)) {
				motor[liftL] = -90;
				motor[liftR] = -90;
				//liftPIDControl(500);
				stacking = false;
				justStacked = false;
				stackPrev = false;
			} else if (isButtonPressed(Btn7LXmtr2)) {
				liftPIDControl(700);
				} else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}
		}

		//Activate curent level
		if (isButtonPressed(Btn8UXmtr2)) {
			stacking = true;
		}

		if (stacking) {
			autoStack(stackLevel);
			} else if (stackPrev) {
			autoStack(prevStackLevel);
			} else if (justStacked) {
			postStacking();
		}

		//Activate Stack
		/*if (isButtonPressed(Btn7RXmtr2)) {
		liftLeftAtPosition = true;
		liftRightAtPosition = true;
		}*/

		//Activate last level
		if (isButtonPressed(Btn8DXmtr2)) {
			stackPrev = true;
		}

		//Increase stack level
		if (isButtonPressed(Btn8UXmtr2) && increaseStackLvl) {
			prevStackLevel ++;
			stackLevel ++;
			increaseStackLvl = false;
		}

		//Deactivate stacking emergency
		if (isButtonPressed(Btn7UXmtr2)) {
			stacking = false;
			justStacked = false;
			stackPrev = false;
		}

		//Deactivate stacking reset to 1
		if (isButtonPressed(Btn7DXmtr2)) {
			stacking = false;
			justStacked = false;
			stackPrev = false;
			stackLevel = 0;
			prevStackLevel = -1;
		}

		//writeDebugStreamLine("stack level %d", stackLevel);
		//writeDebugStreamLine("Prev stack level, %d", prevStackLevel);
		//writeDebugStreamLine("mobile,                                                                           %d", SensorValue[mobilePot]);
		//writeDebugStreamLine("               roller Enc, %d", SensorValue[rollerEnc]);
		//writeDebugStreamLine("arm pot,                                                    %d", SensorValue[armPot]);
		//writeDebugStreamLine("arm power,                                                    %d", armPower );
		//writeDebugStreamLine("left pot, %d", SensorValue[liftLeftPot]);
		//writeDebugStreamLine("right pot,                    %d", SensorValue[liftRightPot]);
		//writeDebugStreamLine("Increase Stack level,                    %d", increaseStackLvl);


		writeDebugStreamLine("right drive enc                    %d", SensorValue[rightDriveEnc]);
		writeDebugStreamLine("left drive enc        %d", SensorValue[leftDriveEnc]);

		//writeDebugStreamLine("Gyro Values,      %d", SensorValue(driveGyro));
		//writeDebugStreamLine("Lift right pot,      %d", SensorValue(liftRightPot));
		//writeDebugStreamLine("						Lift Left pot,      %d", SensorValue(liftLeftPot));

		//datalogAddValueWithTimeStamp(6, SensorValue[liftLeftPot]);
		//datalogAddValueWithTimeStamp(5, SensorValue[liftRightPot]);
		datalogAddValueWithTimeStamp(6, SensorValue[armPot]);

		//datalogAddValueWithTimeStamp(0, SensorValue[liftLeftPot]);
		//datalogAddValueWithTimeStamp(1, SensorValue[liftRightPot]);

		if (isButtonClick(Btn7U)) {
			theaterChaseTask(127, 0, 127, 127, 15000);
		}

		if (isButtonClick(Btn7R)) {
			theaterChaseTask(0, 0, 127, 127, 15000);
		}

		if (isButtonClick(Btn7L)) {
			theaterChaseTask(127, 0, 0, 127, 15000);
		}

		if (isButtonClick(Btn7D)) {
			rainbowCycleTask(0, 15000);
		}

		// --- Choose alliance if both Left & Right LCD Buttons are pressed

		if ((nLCDButtons & (kButtonLeft | kButtonRight)) == (kButtonLeft | kButtonRight)) {
			selectTeamAlliance();
		}

		//writeDebugStreamLine("value Arm pot %d", SensorValue[armPot]);

		wait1Msec(15);
	}
}

task usercontrol()
{
	robotMode = USER_CONTROL;

	if (false) CodePlaceholderForTesting();	// complains if I remove this

	writeDebugStreamLine("Starting User Control...");
	writeDebugStreamLine("Main battery level: %3.2f", nAvgBatteryLevel * 0.001);
	writeDebugStreamLine("Backup battery level: %3.2f", BackupBatteryLevel * 0.001);

	initialize();

	startTask(MotorSlewRateTask);
	startTask(ProcessController);
}

void initialize()
{
	// Library routines thread
	startTask(activateLib);

	// LED strip routines thread
	setupLedStrip();

	//Clear Sensors
	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
	SensorValue[rollerEnc] = 0;

	stacking = false;
	stackPrev = false;
	liftLeftAtPosition = false;
	liftRightAtPosition = false;
	armIsReallyBack = false;
	increaseStackLvl = false;
	justStacked = false;
	outakeFinished = false;

	datalogClear();

	presetLevel = PRESET_LEVEL_ONE;
}

void timerCallback(unsigned int timerId)
{

}

void selectTeamAlliance()
{
	// Defaults
	allianceColor = BLUE_ALLIANCE;
	allianceSide = RIGHT;
	autonomousMode = AUTONOMOUS_MODE_MOBILE_GOAL_20;
	//return;

	//SensorValue[ledGreen] = 0;
	//SensorValue[ledRed] = 0;

	// Zero out encoder positions

	// Clear LCD and turn on backlight
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;

	// Display alliance selection
	displayLCDString(0, 0, " Team Color  ");
	displayLCDString(1, 0, " Blue       Red ");

	bool allianceSelected = false;
	while (!allianceSelected) {	//bIfiRobotDisabled
		// Wait for button press
		switch (getLcdButtons()) {
		case kButtonLeft:
			allianceColor = BLUE_ALLIANCE;
			displayLCDString(1, 0, "[Blue]      Red ");
			allianceSelected = true;
			break;

		case kButtonRight:
			allianceColor = RED_ALLIANCE;
			displayLCDString(1, 0, "Blue       [Red]");
			allianceSelected = true;
			break;
		}

		wait1Msec(10);
	}

	// Display autonomous selection
	wait1Msec(500);

	// Display alliance selection
	displayLCDString(0, 0, " Team Side  ");
	displayLCDString(1, 0, " Left     Right ");

	bool sideSelected = false;
	while (!sideSelected) {	//bIfiRobotDisabled
		// Wait for button press
		switch (getLcdButtons()) {
		case kButtonLeft:
			allianceSide = LEFT;
			displayLCDString(1, 0, "[Left]    Right ");
			sideSelected = true;
			break;

		case kButtonRight:
			allianceSide = RIGHT;
			displayLCDString(1, 0, "Left     [Right]");
			sideSelected = true;
			break;
		}
		wait1Msec(10);
	}



	// Display autonomous selection
	wait1Msec(500);

	displayLCDString(0, 0, "Autonomous Mode ");
	displayLCDString(1, 0, "Full  Min  None ");

	bool autonomousSelected = false;
	int scrollCount = 1;
	byte scrolledAuto = AUTONOMOUS_MODE_MOBILE_GOAL_20;
	while (!autonomousSelected) {
		// Wait for button press
		if(nLCDButtons == 1) {
			scrollCount -= 1;
		}
		if(nLCDButtons == 4) {
			scrollCount += 1;
		}
		if(nLCDButtons == 2) {
			autonomousMode = scrolledAuto;
			autonomousSelected = true;
		}

		switch (scrollCount) {
		case 1:
			scrolledAuto = AUTONOMOUS_MODE_MOBILE_GOAL_20;
			displayLCDString(1, 0, "[1]2 3 4 5 6 7 8 ");
			wait1Msec(200);
			break;

		case 2:
			scrolledAuto = AUTONOMOUS_MODE_STATIONARY;
			displayLCDString(1, 0, " 1[2]3 4 5 6 7 8 ");
			wait1Msec(200);
			break;

		case 3:
			scrolledAuto = AUTONOMOUS_MODE_4_20;
			displayLCDString(1, 0, " 1 2[3]4 5 6 7 8 ");
			wait1Msec(200);
			break;

		case 4:
			scrolledAuto = AUTONOMOUS_MODE_SKILLS;
			displayLCDString(1, 0, " 1 2 3[4]5 6 7 8 ");
			wait1Msec(200);
			break;

		case 5:
			scrolledAuto = AUTONOMOUS_MODE_3_10;
			displayLCDString(1, 0, " 1 2 3 4[5]6 7 8 ");
			wait1Msec(200);
			break;

		case 6:
			scrolledAuto = AUTONOMOUS_MODE_STACK_PIPE;
			displayLCDString(1, 0, " 1 2 3 4 5[6]7 8 ");
			wait1Msec(200);
			break;

		case 7:
			scrolledAuto = AUTONOMOUS_MODE_STACK_BACK;
			displayLCDString(1, 0, " 1 2 3 4 5 6[7]8 ");
			wait1Msec(200);
			break;

		case 8:
			scrolledAuto = AUTONOMOUS_MODE_DRIVE_BLOCK;
			displayLCDString(1, 0, " 1 2 3 4 5 6 7[8]");
			wait1Msec(200);
			break;
		}

		wait1Msec(10);
	}

	wait1Msec(500);

	// Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
}

void initializeGyro() {
	writeDebugStreamLine("Gyro before initialize %d", SensorValue[in8]);

	SensorType(driveGyro) = sensorNone;
	wait1Msec(1000);
	SensorType(driveGyro) = sensorGyro;
	wait1Msec(2000);

	writeDebugStreamLine("Gyro after initialize %d", SensorValue[in8]);
}

void moveArmOut () {
	if (SensorValue[armPot] < 2700) {
		motor[swingingArm] = 120;
		armPower = 120;
		} else if (SensorValue[armPot] >= 2700) {
		motor[swingingArm] = 0;
		armPower = 0;
		armIsReallyBack = false;
	}
}

void moveArmIn () {
	if (SensorValue[armPot] > 840) {
		motor[swingingArm] = -120;
		armPower = -120;
		writeDebugStreamLine("swinging arm pot %d", SensorValue[armPot]);
		} else if (SensorValue[armPot] <= 830) {
		motor[swingingArm] = 0;
		armPower = 0;
		armIsReallyBack = true;
	}
}

void moveArmOutAuto() {
	while(SensorValue[armPot] > 2000) {
		motor[swingingArm] = 100;
	}
	motor[swingingArm] = 0;
}

void moveArm (bool forward) {
	if (forward) {
		moveArmOut();
		} else {
		moveArmIn();
	}
}

void rollerIntake(int speed) {
	motor[roller] = speed;
	rollerSpeed = speed;
	//	writeDebugStreamLine("Set speed %d", rollerSpeed);
}

void rollerOutake(int speed, int time) {
	if (time1[T3] < time) {
		motor[roller] = speed;
		} else {
		motor [roller] = 0;
		outakeFinished = true;
	}
}

void rollerOutakeAuto(int speed, int distance) {
	while (distance > SensorValue[rollerEnc]) {
		motor[roller] = speed;
	}
	motor [roller] = 0;
}

//Drive function for auto
void drive(int left, int right) {
	turnMotor(driveFL, left);
	turnMotor(driveFR, right);
	turnMotor(driveBL, left);
	turnMotor(driveBR, right);
}
//Drive function with encoders for auto
void driveForward(int speed, int distance) {
	while (SensorValue[rightDriveEnc] < distance && SensorValue[leftDriveEnc] < distance) {
		writeDebugStreamLine(" Left Encoder: %d", SensorValue[leftDriveEnc]);
		writeDebugStreamLine(" Right Encoder: %d", SensorValue[rightDriveEnc]);
		writeDebugStreamLine("Moving forward");
		drive(speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
	writeDebugStreamLine("Front Left Encoder: %d", SensorValue[leftDriveEnc]);
	writeDebugStreamLine("Front Right Encoder: %d", SensorValue[rightDriveEnc]);
}

void driveBackward(int speed, int distance) {
	while (SensorValue[rightDriveEnc] > distance && SensorValue[leftDriveEnc] > distance) {
		drive(speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void turnLeft(int speed, int distance) {
	while (SensorValue[leftDriveEnc] < distance && SensorValue[rightDriveEnc] > (-distance)) {
		drive(-speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void turnRight(int speed, int distance) {
	while (SensorValue[leftDriveEnc] > (-distance) && SensorValue[rightDriveEnc] < distance) {
		drive(speed, -speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void clearDriveEnc() {
	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void  moveMobileGoalIn() {
	if (SensorValue[mobilePot] < 3100) {
		motor[mobileGoal] = 127;
		mobileGoalIsOut = true;
		} else {
		motor[mobileGoal] = 40;
		mobileGoalIsOut = false;
	}
}

void moveMobileGoalInAuto() {
	while (SensorValue[mobilePot] > 230) {
		motor[mobileGoal] = 127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalInDistance(int distance) {
	while (SensorValue[mobilePot] > distance) {
		motor[mobileGoal] = 127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalOut() {
	if (SensorValue[mobilePot] > 2000) {
		motor[mobileGoal] = -127;
		mobileGoalIsOut = false;
		} else {
		motor[mobileGoal] = -20;
		mobileGoalIsOut = true;
	}
}

void moveMobileGoalOutAuto() {
	while (SensorValue[mobilePot] < 2000) {
		motor[mobileGoal] = -127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalOutAndDrive(int speed, int distance) {
	while (SensorValue[rightDriveEnc] < distance && SensorValue[leftDriveEnc] < distance) {
		drive(speed, speed);
		while (SensorValue[mobilePot] < 2000) {
			motor[mobileGoal] = -127;
		}
		motor[mobileGoal] = 0;
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void moveMobileGoalInAndDrive(int speed, int distance) {
	while (SensorValue[rightDriveEnc] > distance && SensorValue[leftDriveEnc] > distance) {
		drive(speed, speed);
		while (SensorValue[mobilePot] > 180) {
			motor[mobileGoal] = 127;
		}
		motor[mobileGoal] = 0;
	}
	drive(0, 0);
}


void moveLiftUp(int speed, int distance) {
	if (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) < distance) {
		motor [liftL] = speed;
		motor [liftR] = speed;
		} else {
		motor [liftL] = 0;
		motor [liftR] = 0;
	}
}

void moveLiftUpAuto(int speed, int distance) {
	while (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) < distance) {
		motor [liftL] = speed;
		motor [liftR] = speed;
	}
	motor [liftL] = 0;
	motor [liftR] = 0;
}

void moveLiftDown(int speed, int distance) {
	if (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) > distance) {
		motor [liftL] = -speed;
		motor [liftR] = -speed;
		} else {
		motor [liftL] = 0;
		motor [liftR] = 0;
	}
}

void liftPIDCalculate (int position) {
	float leftCurrent;
	float rightCurrent;

	float integralAcitveZone = 100;

	float leftProportion;
	float sharedIntegral;
	float leftDerivative;
	float rightProportion;
	float rightDerivative;

	float liftLeftError;
	float liftRightError;
	float errorT;
	float leftLastPot;
	float rightLastPot;

	float leftPot = SensorValue[liftLeftPot];
	float rightPot = SensorValue[liftRightPot];

	//Find lift error
	liftLeftError = position - leftPot;
	liftRightError = position - rightPot;

	leftProportion = liftLeftError * liftkp;
	rightProportion = liftRightError * liftkp;

	sharedIntegral = errorT * liftki * 0.025;

	leftDerivative = ((leftPot - leftLastPot) * liftkd)/0.025;
	rightDerivative = ((rightPot - rightLastPot) * liftkd)/0.025;

	//Integral
	errorT += liftLeftError;
	if (sharedIntegral > 80) {
		sharedIntegral = 80;
		} else if (sharedIntegral < -80) {
		sharedIntegral = -80;
	}

	leftCurrent = leftProportion + sharedIntegral + leftDerivative;
	rightCurrent = rightProportion + sharedIntegral + rightDerivative;

	/*if (abs(leftPot - leftLastPot) <= 1) {
		liftLeftAtPosition = true;
		} else {
		liftLeftAtPosition = false;
	}
	if (abs(leftPot - leftLastPot) <= 1) {
		liftRightAtPosition = true;
		} else {
		liftRightAtPosition = false;
	}*/

	if (leftCurrent > 127) {
		leftCurrent = 127;
	}
	if (rightCurrent > 127) {
		rightCurrent = 127;
	}
	if (leftCurrent < -127) {
		leftCurrent = -127;
	}
	if (rightCurrent < -127) {
		rightCurrent = -127;
	}

	motor[liftL] = leftCurrent;
	motor[liftR] = leftCurrent;

	//writeDebugStreamLine("left pot %d", leftPot);
	//writeDebugStreamLine("             right pot %d", rightPot);
	//writeDebugStreamLine("arm %d", armIsReallyBack);
	//writeDebugStreamLine("  left integral %d", sharedIntegral);
	//writeDebugStreamLine("                          right integral %d", rightIntegral);
	//writeDebugStreamLine("position %d", position);
	//writeDebugStreamLine("          left error %d", liftLeftError);
	//writeDebugStreamLine("                  right error %d", liftRightError);
	//writeDebugStreamLine("                     left curent %d", leftCurrent);
	//writeDebugStreamLine("                                    right curent %d", rightCurrent);
	writeDebugStreamLine("                               Change in position %d", (leftPot - leftLastPot));
	writeDebugStreamLine("  liftLeftAtPosition %d", liftLeftAtPosition);
	//writeDebugStreamLine("  curent %d", leftCurrent);
	//writeDebugStreamLine("  derivative %f", leftDerivative);
	//writeDebugStreamLine("  integral %f", sharedIntegral);
	//writeDebugStreamLine("  proportion %f", leftProportion);

	//datalogAddValueWithTimeStamp(0, leftPot);
	//datalogAddValueWithTimeStamp(1, rightPot);
	//datalogAddValueWithTimeStamp(2, position);
	//datalogAddValueWithTimeStamp(3, leftCurrent);

	leftLastPot = leftPot;
	rightLastPot = rightPot;

	clearTimer(T4);
}

void liftPIDControl (int position) {
	if (time1[T4] > 25) {
		liftPIDCalculate(position);
	}
}

void checkLiftPos (int height) {
	if (SensorValue[liftLeftPot] >= height - 500) {
		liftLeftAtPosition = true;
	} else {
		liftLeftAtPosition = false;
	}
	if (SensorValue[liftRightPot] >= height - 500) {
		liftRightAtPosition = true;
	} else {
		liftRightAtPosition = false;
	}
}

void autoStackStep(int liftPos) {
	//Check if lift reaches height
	checkLiftPos(liftPos);

	if (outakeFinished) {
		stacking = false;
		stackPrev = false;
		justStacked = true;
		liftLeftAtPosition = false;
		liftRightAtPosition = false;
		armIsReallyBack = false;
		increaseStackLvl = true;
		writeDebugStreamLine("stage 4");
		} else {
		if (!armIsReallyBack) {
			liftPIDControl(liftPos);
			writeDebugStreamLine("stage 1");
			} else if (time1[T1] <= autoStackDownTime) {
			motor[liftL] = -60;
			motor[liftR] = -60;
			clearTimer(T3);
			} else if (time1[T1] >= autoStackDownTime) {
			rollerOutake(-127, autoStackOutTime);
			liftPIDControl(liftPos + autoStackExraHeight);
			writeDebugStreamLine("Second Pid and Outake");
		}

		if (liftLeftAtPosition /*&& liftRightAtPosition*/ && !armIsReallyBack) {
			moveArmIn();
			liftPIDControl(liftPos);
			//Not auto stacking stuff
			//armIsBack = false;
			writeDebugStreamLine("stage 2");
			clearTimer(T1);
		}
	}
}

void autoStack(int level) {
	switch (level) {
	case PRESET_LEVEL_ONE:
		autoStackStep(h1);
		break;

	case PRESET_LEVEL_TWO:
		autoStackStep(h2);
		break;

	case PRESET_LEVEL_THREE:
		autoStackStep(h3);
		break;

	case PRESET_LEVEL_FOUR:
		autoStackStep(h4);
		break;

	case PRESET_LEVEL_FIVE:
		autoStackStep(h5);
		break;

	case PRESET_LEVEL_SIX:
		autoStackStep(h6);
		break;

	case PRESET_LEVEL_SEVEN:
		autoStackStep(h7);
		break;

	case PRESET_LEVEL_EIGHT:
		autoStackStep(h8);
		break;

	case PRESET_LEVEL_NINE:
		autoStackStep(h9);
		break;

	case PRESET_LEVEL_TEN:
		autoStackStep(h10);
		break;

	case PRESET_LEVEL_ELEVEN:
		autoStackStep(h11);
		break;

	case PRESET_LEVEL_TWELVE:
		autoStackStep(h12);
		break;

	case PRESET_LEVEL_THIRTEEN:
		autoStackStep(h13);
		break;

	case PRESET_LEVEL_FOURTEEN:
		autoStackStep(h14);
		break;
	}
}

void postStacking() {
	moveArmOut();
	//armIsBack = true;
	if (!armIsReallyBack) {
		if (SensorValue[liftLeftPot] > 500 /*&& SensorValue[liftRightPot] > 500*/) {
			motor[liftL] = -127;
			motor[liftR] = -127;
			//liftPIDControl(350);
		}
	} else {
		motor[liftL] = -15;
		motor[liftR] = -15;
	}
	if (SensorValue[liftLeftPot] <= 370 /*&& SensorValue[liftRightPot] <= 370*/) {
		motor[liftL] = 0;
		motor[liftR] = 0;
		justStacked = false;
	}
	outakeFinished = false;
}

void autoDrivePIDCalculate (int distance) {
	float encAverage = (SensorValue[leftDriveEnc]+SensorValue[rightDriveEnc])/2;

	float integralAcitveZone = 100;

	float error;
	float proportion;
	float integral;
	float derivative;

	float errorT;
	float lastError;

	float current;

	//Find Distance error
	error = distance - encAverage;

	//Set proportion
	proportion = error * drivekp;

	integral = errorT * driveki * 0.025;

	derivative = ((error - lastError) * drivekd)/0.025;


	//Calculate integral
	//left
	errorT += error;
	if (integral > 80) {
		integral = 80;
	} else if (integral < -80) {
		integral = -80;
	}

	//Set current
	current = proportion + integral + derivative;
	driveCurrent = proportion + integral + derivative;

	/*if (abs(error) <= drivePositionError) {
		current = 0;
	}

	if (abs(error) <= driveTurnPositionError) {
		gyroCurrent = 0;
	}*/

	//Check that drive has stopped
	if (abs(error - lastError) <= 2) {
		driveAtPosition = true;
		} else {
		driveAtPosition = false;
	}

	if (current > 127) {
		current = 127;
	}
	if (current < -127) {
		current = -127;
	}


	motor[driveBL] = current;
	motor[driveFL] = current;
	motor[driveBR] = current;
	motor[driveFR] = current;

	//writeDebugStreamLine("Current Angle %d", encAverage);
	//writeDebugStreamLine("            error %d", error);
	//writeDebugStreamLine("            last error %d", lastError);
	writeDebugStreamLine("        integral %d", integral);
	//writeDebugStreamLine("             error total %d", errorT);
	writeDebugStreamLine("                      derivative %d", derivative);
	//writeDebugStreamLine("           last error %d", lastError);
	//writeDebugStreamLine("             drive current 2/ %d", current);
	writeDebugStreamLine("proportion %d", proportion);
	//writeDebugStreamLine("             error %d", error);
	//writeDebugStreamLine("             distance %d", distance);

	//datalogAddValueWithTimeStamp(0, error);
	//datalogAddValueWithTimeStamp(0, encAverage);
	/*datalogAddValueWithTimeStamp(2, integral);
	datalogAddValueWithTimeStamp(3, derivative);*/
	//datalogAddValueWithTimeStamp(1, distance);
	//datalogAddValueWithTimeStamp(2, current);
	//datalogAddValueWithTimeStamp(5, error);

	lastError = error;

	//Make sure the loop happens consistantly
	clearTimer(T1);
}

void autoDrivePIDControl (int distance, bool time) {
	if (time) {
		if (time1[T1] > 25) {
			autoDrivePIDCalculate(distance);
		}
	} else {
		autoDrivePIDCalculate(distance);
	}
}

void autoGyroPIDCalculate (int setAngle) {
	float angle = SensorValue(driveGyro);

	float integralAcitveZone = 1000;

	float proportion;
	float integral;
	float derivative;

	float errorT;
	float lastError;

	float current;

	//Find Angle error
	turnError = setAngle - angle;

	//Set proportion
	proportion = turnError * turnkp;

	integral = errorT * turnki * 0.025;

	derivative = ((turnError - lastError) * turnkd)/0.025;

	//Calculate integral
	errorT += turnError;
	if (integral > 80) {
		integral = 80;
	} else if (integral < -80) {
		integral = -80;
	}

	//Set current
	current = proportion + integral + derivative;

	/*if (abs(turnError) <= turnPositionError) {
		current = 0;
	}*/

	//Check that turn has stopped
	/*if (abs(turnError) <= turnPositionError) {
		turnAtPosition = true;
		} else {
		turnAtPosition = false;
	}*/

	if (current > 127) {
		current = 127;
	}
	if (current < -127) {
		current = -127;
	}

	//Send to motors
	motor[driveBL] = -current;
	motor[driveFL] = -current;
	motor[driveBR] = current;
	motor[driveFR] = current;

	//writeDebugStreamLine("Current Angle %d", currentAngle);
	//writeDebugStreamLine("            turn error %d", turnError);
	/*writeDebugStreamLine("             integral %d", integral);
	writeDebugStreamLine("             error total %d", errorT);
	writeDebugStreamLine("             derivative %d", derivative);
	writeDebugStreamLine("           last error %d", lastError);*/
	//writeDebugStreamLine("             angle current 2/ %d", current);

	//datalogAddValueWithTimeStamp(4, turnError);
	datalogAddValueWithTimeStamp(0, angle);
	datalogAddValueWithTimeStamp(1, setAngle);
	datalogAddValueWithTimeStamp(2, current);
	/*datalogAddValueWithTimeStamp(2, integral);
	datalogAddValueWithTimeStamp(3, derivative);
	datalogAddValueWithTimeStamp(4, current);*/
	//datalogAddValueWithTimeStamp(4, turnError);

	lastError = turnError;

	clearTimer(T1);
}

void autoGyroPIDControl (int setAngle) {
	if (time1[T1] > 25) {
		autoGyroPIDCalculate(setAngle);
	}
}

void autoDriveGyroPIDCalculate (int setAngle, int distance) {
	autoDrivePIDControl(distance, false);

	float angle = SensorValue(driveGyro);
	float gyroCurrent;

	//Find Angle error
	turnError = setAngle - angle;

	gyroCurrent = turnError * driveTurnkp;

	//Assign power to motors
	motor[driveBL] = driveCurrent - gyroCurrent;
	motor[driveFL] = driveCurrent - gyroCurrent;
	motor[driveBR] = driveCurrent + gyroCurrent;
	motor[driveFR] = driveCurrent + gyroCurrent;

	//Limit power to motors
	if (gyroCurrent > maxTurnPower) {
		gyroCurrent = maxTurnPower;
	}
	if (gyroCurrent < -maxTurnPower) {
		gyroCurrent = -maxTurnPower;
	}

	/*if (abs(turnError) <= turnDrivePositionError) {
		gyroCurrent = 0;
	}*/

	if (driveCurrent > 127 - maxTurnPower) {
		driveCurrent = (127 - maxTurnPower);
	}
	if (driveCurrent < -(127 - maxTurnPower)) {
		driveCurrent = -(127 - maxTurnPower);
	}

	/*writeDebugStreamLine("Angle current %d", gyroCurrent);
	writeDebugStreamLine("Drive current %d", driveCurrent);
	writeDebugStreamLine("             overall  current left %d", overallCurrentLeft);
	writeDebugStreamLine("             overall  current right %d", overallCurrentRight);*/
	//writeDebugStreamLine("             gyro %d", SensorValue[driveGyro]);

	//datalogAddValueWithTimeStamp(3, setAngle);
	//datalogAddValueWithTimeStamp(4, angle);
	//datalogAddValueWithTimeStamp(5, gyroCurrent);

	clearTimer(T1);
}

void autoDriveGyroPIDControl (int setAngle, int distance) {
	if (time1[T1] > 25) {
			autoDriveGyroPIDCalculate(setAngle, distance);
	}
}
void collectMobileGoal() {
	while (time1[T2] < 3000) {

		moveLiftUp(90, 400);

		//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
				} else {
				motor[mobileGoal] = -50;
			}

		if (time1[T2] > 100) {
			autoDriveGyroPIDControl(0, 1850);
		}
	}
}

void intakeMobileGoalAndStackFirstCone() {
	while (time1[T2] < 2000) {

		//Move mobile goal lifter out
		if (mobileGoalIsOut) {
			moveMobileGoalIn();
			} else {
			motor[mobileGoal] = 40;
		}

		if (time1[T2] > 700) {
			moveLiftDown(60, 400);
		}

		if (time1[T2] > 700 && time1[T2] < 900) {
				motor[roller] = -100;
			}

		if (time1[T2] > 1000) {
				motor[roller] = 127;
				moveArmOut();
				autoDriveGyroPIDControl(0, 200);
			}

		if (time1[T2] > 1400) {
			motor[roller] = 40;
			moveLiftUp(80, 450);
		}

		if (time1[T2] > 1550) {
			moveArmIn();
		}

	}
}

void stackSecondConeAndCollectThirdCone() {
	while (time1[T2] < 2000) {

		moveLiftDown(80, 350);

		if (time1[T2] > 300) {
			motor[roller] = -100;
			moveLiftUp(80, 450);
		}

		if (time1[T2] > 400) {
			autoDriveGyroPIDControl(0, 200);
			moveArmOut();
			motor[roller] = 100;
		}

		if (time1[T2] > 1000) {
			motor[roller] = 40;
			moveLiftUp(80, 450);
		}

		if (time1[T2] > 1250) {
			moveArmIn();
		}

	}
}
