#pragma config(Sensor, in1,    mobilePot,      sensorPotentiometer)
#pragma config(Sensor, in2,    liftLeftPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    liftRightPot,   sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightDriveEnc,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDriveEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rollerEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  MOSI,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  SCLK,           sensorDigitalOut)
#pragma config(Motor,  port1,           mobileGoal,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveBL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveBR,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port4,           driveFL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveFR,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           swingingArm,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           roller,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           liftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Declare VEX as the robot platform

#pragma platform(VEX)

// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

// **** Important programmer notes ****
//
// When upgrading ROBOTC the Robot Platform Settings are lost and must be reset
// otherwise compiler error will result. Ensure the following are set:
// 		Robot -> Platform Type -> VEX 2.0 Cortex
// 		Robot -> Platform Type -> VEX Robotics -> VEX 2.0 Cortex
// 		Robot -> Platform Type -> Natural Language (PLTW)
//
//
// Note: Sometime when upgrading FW on the controller and/or joystick, the FW for the
//       VEXNet Keys must also be upgraded. The symptom of needing this upgrade is a
//       failure of the controller and joystick to communicate with each other.
//
//
// Note: When RobotC refuses to download code to the robot, first try manually selecting the
//       COM port. If that doesn't work then it may be necessary reload the firmware. First
//       update the main FW and then the RobotC FW. Don't forget to rename robot afterwards.
//
//
// Variable info:
//
//		int, short, word - 2 bytes
//		long - 4 bytes
//		SensorValue() returns 2 byte value

// Control debugger windows by defining these pragmas
#pragma DebuggerWindows("debugStream")

#include "Team8800Lib.c"		// Utility routines to simplify programming
#include "Team8800Led.c"		// Routines to control the LED strip
#include "MultiTask.c"  // Motor slew control

// Delcarations

// Initialize
void initialize();
void selectTeamAlliance();

// Controller Input
//void processController();

// Autonomous
//void autonomousRoutines();

// Robot Action

//Functions
void moveLiftDown(int speed, int distance);
void moveArmOut();
void moveArmIn();
void moveArm(bool forward);
void moveLiftUp(int speed, int distance);
void moveLiftUp4(int height);
void moveLiftUp5(int height);
void rollerIntake(int speed);
void rollerOutake(int speed, int distance);

void checkPositions();

bool buttonToggle(TVexJoysticks buttonOneName, TVexJoysticks buttonTwoName);
void checkButtonToggle(TVexJoysticks buttonOneName, TVexJoysticks buttonTwoName);

//Auto Functions
void moveMobileGoalOutAndDrive(int speed, int distance);
void autoLiftControl (int height);
void drive(int left, int right);
void driveForward(int speed, int distance);
void driveBackward(int speed, int distance);
void turnLeft(int speed, int distance);
void clearDriveEnc();
void moveMobileGoalOut();
void moveMobileGoalIn();

// Constants and global vars
const byte MIN_JOYSTICK_THRESHOLD = 30;

const byte RED_ALLIANCE = 1;
const byte BLUE_ALLIANCE = 2;
byte allianceColor = BLUE_ALLIANCE;

const byte LEFT = 1;
const byte RIGHT = 2;
byte allianceSide = RIGHT;

const byte AUTONOMOUS_MODE_MOBILE_GOAL_20 = 1;
const byte AUTONOMOUS_MODE_CUBE_BACK_STAR = 2;
const byte AUTONOMOUS_MODE_FENCE = 3;
const byte AUTONOMOUS_MODE_SKILLS = 4;
const byte AUTONOMOUS_MODE_STACK_DRIVE = 5;
const byte AUTONOMOUS_MODE_STACK_PIPE = 6;
const byte AUTONOMOUS_MODE_STACK_BACK = 7;
const byte AUTONOMOUS_MODE_DRIVE_BLOCK = 8;
byte autonomousMode = AUTONOMOUS_MODE_MOBILE_GOAL_20;

const byte PRESET_LEVEL_ONE = 1;
const byte PRESET_LEVEL_TWO = 2;
const byte PRESET_LEVEL_THREE = 3;
const byte PRESET_LEVEL_FOUR = 4;
const byte PRESET_LEVEL_FIVE = 5;
const byte PRESET_LEVEL_SIX = 6;
const byte PRESET_LEVEL_SEVEN = 7;
const byte PRESET_LEVEL_EIGHT = 8;
const byte PRESET_LEVEL_NINE = 9;
const byte PRESET_LEVEL_TEN = 10;
const byte PRESET_LEVEL_ELEVEN = 11;
const byte PRESET_LEVEL_TWELVE = 12;
const byte PRESET_LEVEL_THIRTEEN = 13;
const byte PRESET_LEVEL_FOURTEEN = 14;
const byte PRESET_LEVEL_FIFTEEN = 15;
byte presetLevel = PRESET_LEVEL_ONE;

const byte DRIVE_SLOW_FORWARD = 60;
const byte DRIVE_SLOW_REVERSE = -60;

unsigned long autonomousStartTime;

const byte AUTONOMOUS = 1;
const byte USER_CONTROL = 2;
byte robotMode = 1;

bool presetLevelActive = false;
bool presetLevelJustActive = false;

bool boingyPointOn = true;
bool armBack = false;
bool armFront = true;

bool armIsBack;
bool armIsBackLvl1and2;
bool armIsForward;
bool liftLeftIsPosition4;
bool liftRightIsPosition4 = false;
bool liftIsPosition4Again = false;
bool liftIsPosition5;
bool liftIsPosition6;
bool liftIsDown = false;

bool rollerIntaking = false;
bool rollerOutaking = false;

bool btnSixUPressed = false;
bool btnSixDPressed = false;

bool presetLevelScrollUp = false;
bool presetLevelScrollDown = false;

int level4Height = 85;
int level5Height = 115;
int level6Height = 260;
int level7Height = 370;
int level8Height = 470;
int level9Height = 570;
int level10Height = 800;
int level11Height = 100;
int level12Height = 120;
int level13Height = 120;
int level14Height = 120;
int level15Height = 120;

int liftError = 20;
int armError = 20;

float liftLeftError;
float liftRightError;
float leftErrorT;
float rightErrorT;

float leftkp = 0.3;
float leftki = 0.0000009;

float rightkp = 0.3;
float rightki = 0.000001;


float leftCurrent;
float rightCurrent;

float integralAcitveZone = 500;

float leftProportion;
float leftIntegral;
float rightProportion;
float rightIntegral;

int armPotPosition = 2900;
int getToArmSpeed = 35;

int rollerRotationsOut = 0;

int savedValueHeight;
int savedValueHeight4;

int rollerSpeed;

void pre_auton()
{
	bStopTasksBetweenModes = true;

	clearDebugStream();
	writeDebugStreamLine("Pre-Autonomous...");

	// Select alliance using LCD and indicate selection with LEDs
	selectTeamAlliance();
}

task autonomousRoutines()
{
	switch (autonomousMode) {
	case AUTONOMOUS_MODE_MOBILE_GOAL_20:
		if (allianceSide == LEFT && allianceColor == RED_ALLIANCE) {
			motor [roller] = 40;

			//move lift up
			moveLiftUp(100, 1900);

			waitInMilliseconds(200);

			clearDriveEnc();

			//mobile goal out
			moveMobileGoalOutAndDrive(50, 1100);

			//drive forward
			//driveForward (90, 1100);

			waitInMilliseconds(200);

			//intake the mobile goal
			moveMobileGoalIn();

			waitInMilliseconds(150);

			//move lift down
			moveLiftDown(50, 2400);

			waitInMilliseconds(200);

			SensorValue[rollerEnc] = 0;

			rollerOutake(-100, 300);

			waitInMilliseconds(200);

			clearDriveEnc();

			//drive backward
			driveBackward(-110, -500);

			waitInMilliseconds(300);

			clearDriveEnc();

			turnLeft(127, 150);

			waitInMilliseconds(200);

			clearDriveEnc();

			driveBackward(-100, -750);

			waitInMilliseconds(200);

			clearDriveEnc();

			turnLeft(100, 340);

			waitInMilliseconds(300);

			clearDriveEnc();

			driveBackward(-120, -40);

			waitInMilliseconds(200);

			moveLiftUp(100, 1500);

			clearDriveEnc();

			driveForward(127, 600);

			waitInMilliseconds(200);

			drive(70, 70);
			waitInMilliseconds(500);
			drive(0, 0);

			waitInMilliseconds(400);

			moveMobileGoalOut();

			waitInMilliseconds(200);

			drive(-50, -50);
			waitInMilliseconds(700);
			drive(0, 0);

			waitInMilliseconds(200);

			moveMobileGoalIn();

			driveBackward(-100, -500);



		} else if (allianceSide == RIGHT && allianceColor == RED_ALLIANCE) {

	}

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}
		break;

	case AUTONOMOUS_MODE_CUBE_BACK_STAR:

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}
		break;

	case AUTONOMOUS_MODE_FENCE:

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		break;

	case AUTONOMOUS_MODE_SKILLS:


		break;

	case AUTONOMOUS_MODE_STACK_DRIVE:

		break;

	case AUTONOMOUS_MODE_STACK_PIPE:

		break;

	case AUTONOMOUS_MODE_STACK_BACK:

		break;

	case AUTONOMOUS_MODE_DRIVE_BLOCK:

		break;
	}
}

task autonomous()
{
	robotMode = AUTONOMOUS;

	autonomousStartTime = nSysTime;
	writeDebugStreamLine("Starting Autonomous...");

	if (false) AutonomousCodePlaceholderForTesting();  // complains if I remove this

	initialize();
	startTask(autonomousRoutines);
}

task ProcessController() {
	while(true) {

		/*
		Main Controller:
		joysticks = drive

		Partner Contorller:
		right joystick = catapult
		*/

		// --- Joysticks to control robot driving (main controller only)

		static byte rightJoystickY, leftJoystickY, prevRightJoystickY = 0, prevLeftJoystickY = 0;

		rightJoystickY = readRightJoystickYAxis();
		leftJoystickY = readLeftJoystickYAxis();

		static bool rightDriveMoving = false;
		if (abs(rightJoystickY) > MIN_JOYSTICK_THRESHOLD) {
			rightDriveMoving = true;
			motorReq[driveFR] = rightJoystickY;
			motorReq[driveBR] = rightJoystickY;
			writeDebugStreamLine("Right: %d%%", rightJoystickY);
			} else {
			rightDriveMoving = false;
			motorReq[driveFR] = 0;
			motorReq[driveBR] = 0;
		}

		static bool leftDriveMoving = false;
		if (abs(leftJoystickY) > MIN_JOYSTICK_THRESHOLD) {
			leftDriveMoving = true;
			motorReq[driveFL] = leftJoystickY;
			motorReq[driveBL] = leftJoystickY;
			writeDebugStreamLine("Left: %d%%", leftJoystickY);
			} else {
			leftDriveMoving = false;
			motorReq[driveFL] = 0;
			motorReq[driveBL] = 0;
		}

		/*checkButtonToggle(Btn8LXmtr2, Btn8RXmtr2);
		//Arm controls on bumpers
		if (buttonToggle(Btn8LXmtr2, Btn8RXmtr2)) {
			moveArm(true);
		} else if (!buttonToggle(Btn8LXmtr2, Btn8RXmtr2)) {
			moveArm(false);
		} else {
			motor[swingingArm] = 0;
		}*/
		if (isButtonPressed(Btn8LXmtr2)) {
			motor[swingingArm] = 127;
		} else if (isButtonPressed(Btn8RXmtr2)) {
			motor[swingingArm] = -127;
		} else {
			motor[swingingArm] = 0;
		}

		//Mobile Goal control on joystick
		if (isButtonPressed(Btn6U)) {
			motor[mobileGoal] = 127;
		} else if (isButtonPressed(Btn6D)) {
			motor[mobileGoal] = -127;
		} else {
			motor[mobileGoal] = 0;
		}

		//Roller control
		if (isButtonPressed(Btn6DXmtr2)) {
			motor[roller] = -127;
			} else if (isButtonPressed(Btn6UXmtr2)) {
			motor[roller] = 127;
			} else {
			motor[roller] = 30;
		}

		//Move lift
		if (isButtonPressed(Btn5UXmtr2)) {
			motor[liftL] = 127;
			motor[liftR] = 127;
			} else if (isButtonPressed(Btn5DXmtr2)) {
			motor[liftL] = -127;
			motor[liftR] = -127;
			} else {
			motor[liftL] = 0;
			motor[liftR] = 0;

			//writeDebugStreamLine("lift Left potentiometer, %d", SensorValue[liftLeftPot]);
			//writeDebugStreamLine("lift Right, %d", SensorValue[liftRightPot]);
			//writeDebugStreamLine("Left Enc, %d", SensorValue[leftDriveEnc]);
			//writeDebugStreamLine("mobile, %d", SensorValue[mobilePot]);
			writeDebugStreamLine("roller Enc, %d", SensorValue[rollerEnc]);
		}

		if (isButtonClick(Btn8UXmtr2)) {
			theaterChaseTask(127, 0, 127, 127, 15000);
		}

		if (isButtonClick(Btn8RXmtr2)) {
			theaterChaseTask(0, 0, 127, 127, 15000);
		}

		if (isButtonClick(Btn8LXmtr2)) {
			theaterChaseTask(127, 0, 0, 127, 15000);
		}


		// --- Choose alliance if both Left & Right LCD Buttons are pressed

		if ((nLCDButtons & (kButtonLeft | kButtonRight)) == (kButtonLeft | kButtonRight)) {
			selectTeamAlliance();
		}

		//writeDebugStreamLine("value Arm pot %d", SensorValue[armPot]);

		wait1Msec(15);
	}
}

task usercontrol()
{
	robotMode = USER_CONTROL;

	if (false) UserControlCodePlaceholderForTesting();	// complains if I remove this

	writeDebugStreamLine("Starting User Control...");
	writeDebugStreamLine("Main battery level: %3.2f", nAvgBatteryLevel * 0.001);
	writeDebugStreamLine("Backup battery level: %3.2f", BackupBatteryLevel * 0.001);

	initialize();

	startTask(MotorSlewRateTask);
	startTask(ProcessController);
}

void initialize()
{
	// Library routines thread
	startTask(activateLib);

	// LED strip routines thread
	setupLedStrip();

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
	SensorValue[rollerEnc] = 0;

	datalogClear();

	presetLevel = PRESET_LEVEL_ONE;
}

void timerCallback(unsigned int timerId)
{

}

void selectTeamAlliance()
{
	// Defaults
	allianceColor = BLUE_ALLIANCE;
	allianceSide = RIGHT;
	autonomousMode = AUTONOMOUS_MODE_MOBILE_GOAL_20;
	//return;

	//SensorValue[ledGreen] = 0;
	//SensorValue[ledRed] = 0;

	// Zero out encoder positions

	// Clear LCD and turn on backlight
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;

	// Display alliance selection
	displayLCDString(0, 0, " Team Color  ");
	displayLCDString(1, 0, " Blue       Red ");

	bool allianceSelected = false;
	while (!allianceSelected) {	//bIfiRobotDisabled
		// Wait for button press
		switch (getLcdButtons()) {
		case kButtonLeft:
			allianceColor = BLUE_ALLIANCE;
			displayLCDString(1, 0, "[Blue]      Red ");
			allianceSelected = true;
			break;

		case kButtonRight:
			allianceColor = RED_ALLIANCE;
			displayLCDString(1, 0, "Blue       [Red]");
			allianceSelected = true;
			break;
		}

		wait1Msec(10);
	}

	// Display autonomous selection
	wait1Msec(500);

	// Display alliance selection
	displayLCDString(0, 0, " Team Side  ");
	displayLCDString(1, 0, " Left     Right ");

	bool sideSelected = false;
	while (!sideSelected) {	//bIfiRobotDisabled
		// Wait for button press
		switch (getLcdButtons()) {
		case kButtonLeft:
			allianceSide = LEFT;
			displayLCDString(1, 0, "[Left]    Right ");
			sideSelected = true;
			break;

		case kButtonRight:
			allianceSide = RIGHT;
			displayLCDString(1, 0, "Left     [Right]");
			sideSelected = true;
			break;
		}

		wait1Msec(10);
	}



	// Display autonomous selection
	wait1Msec(500);

	displayLCDString(0, 0, "Autonomous Mode ");
	displayLCDString(1, 0, "Full  Min  None ");

	bool autonomousSelected = false;
	int scrollCount = 1;
	byte scrolledAuto = AUTONOMOUS_MODE_MOBILE_GOAL_20;
	while (!autonomousSelected) {
		// Wait for button press
		if(nLCDButtons == 1) {
			scrollCount -= 1;
		}
		if(nLCDButtons == 4) {
			scrollCount += 1;
		}
		if(nLCDButtons == 2) {
			autonomousMode = scrolledAuto;
			autonomousSelected = true;
		}

		switch (scrollCount) {
		case 1:
			scrolledAuto = AUTONOMOUS_MODE_MOBILE_GOAL_20;
			displayLCDString(1, 0, "[1]2 3 4 5 6 7 8 ");
			wait1Msec(200);
			break;

		case 2:
			scrolledAuto = AUTONOMOUS_MODE_CUBE_BACK_STAR;
			displayLCDString(1, 0, " 1[2]3 4 5 6 7 8 ");
			wait1Msec(200);
			break;

		case 3:
			scrolledAuto = AUTONOMOUS_MODE_FENCE;
			displayLCDString(1, 0, " 1 2[3]4 5 6 7 8 ");
			wait1Msec(200);
			break;

		case 4:
			scrolledAuto = AUTONOMOUS_MODE_SKILLS;
			displayLCDString(1, 0, " 1 2 3[4]5 6 7 8 ");
			wait1Msec(200);
			break;

		case 5:
			scrolledAuto = AUTONOMOUS_MODE_STACK_DRIVE;
			displayLCDString(1, 0, " 1 2 3 4[5]6 7 8 ");
			wait1Msec(200);
			break;

		case 6:
			scrolledAuto = AUTONOMOUS_MODE_STACK_PIPE;
			displayLCDString(1, 0, " 1 2 3 4 5[6]7 8 ");
			wait1Msec(200);
			break;

		case 7:
			scrolledAuto = AUTONOMOUS_MODE_STACK_BACK;
			displayLCDString(1, 0, " 1 2 3 4 5 6[7]8 ");
			wait1Msec(200);
			break;

		case 8:
			scrolledAuto = AUTONOMOUS_MODE_DRIVE_BLOCK;
			displayLCDString(1, 0, " 1 2 3 4 5 6 7[8]");
			wait1Msec(200);
			break;
		}

		wait1Msec(10);
	}

	wait1Msec(500);

	// Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
}

void moveArmOut () {
	if (SensorValue[armPot] > 25) {
		motor[swingingArm] = 115;
	} else if (SensorValue[armPot] <= 25) {
		motor[swingingArm] = 0;
	}
}

void moveArmIn () {
	if (SensorValue[armPot] < 2115) {
		motor[swingingArm] = -125;
	} else if (SensorValue[armPot] >= 2115) {
		motor[swingingArm] = 0;
	}
}

void moveArm (bool forward) {
	if (forward) {
		moveArmOut();
	} else {
		moveArmIn();
	}
}

void rollerIntake(int speed) {
	motor[roller] = speed;
	rollerSpeed = speed;
	//	writeDebugStreamLine("Set speed %d", rollerSpeed);
}

void rollerOutake(int speed, int distance) {
	while (distance > SensorValue[rollerEnc]) {
	 motor[roller] = speed;
	 writeDebugStreamLine("Roller Enc %d", SensorValue[rollerEnc]);
	}
	motor [roller] = 0;
}

//Drive function for auto
void drive(int left, int right) {
	turnMotor(driveFL, left);
	turnMotor(driveFR, right);
	turnMotor(driveBL, left);
	turnMotor(driveBR, right);
}
//Drive function with encoders for auto
void driveForward(int speed, int distance) {
	while (SensorValue[rightDriveEnc] < distance && SensorValue[leftDriveEnc] < distance) {
		writeDebugStreamLine(" Left Encoder: %d", SensorValue[leftDriveEnc]);
		writeDebugStreamLine(" Right Encoder: %d", SensorValue[rightDriveEnc]);
		writeDebugStreamLine("Moving forward");
		drive(speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
	writeDebugStreamLine("Front Left Encoder: %d", SensorValue[leftDriveEnc]);
	writeDebugStreamLine("Front Right Encoder: %d", SensorValue[rightDriveEnc]);
}

void driveBackward(int speed, int distance) {
	while (SensorValue[rightDriveEnc] > distance && SensorValue[leftDriveEnc] > distance) {
		drive(speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void turnLeft(int speed, int distance) {
	while (SensorValue[leftDriveEnc] < distance && SensorValue[rightDriveEnc] > (-distance)) {
		drive(-speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}


void clearDriveEnc() {
	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void moveMobileGoalIn() {
	while (SensorValue[mobilePot] > 180) {
		motor[mobileGoal] = 127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalOut() {
	while (SensorValue[mobilePot] < 2170) {
		motor[mobileGoal] = -127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalOutAndDrive(int speed, int distance) {
		while (SensorValue[rightDriveEnc] < distance && SensorValue[leftDriveEnc] < distance) {
		drive(speed, speed);
			while (SensorValue[mobilePot] < 2170) {
			motor[mobileGoal] = -127;
	}
	motor[mobileGoal] = 0;

	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}



void moveLiftUp(int speed, int distance) {
	while (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) > distance) {
		motor [liftL] = speed;
		motor [liftR] = speed;
	}
	motor [liftL] = 0;
	motor [liftR] = 0;
}

void moveLiftDown(int speed, int distance) {
	while (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) < distance) {
		motor [liftL] = -speed;
		motor [liftR] = -speed;
	}
	motor [liftL] = 0;
	motor [liftR] = 0;
}

bool buttonToggle(TVexJoysticks buttonOneName, TVexJoysticks buttonTwoName) {
	bool position;
	if (isButtonPressed(buttonOneName)) {
		position = true;
	} else if (isButtonPressed(buttonTwoName)) {
		position = false;
	}
	return position;
}

void checkButtonToggle(TVexJoysticks buttonOneName, TVexJoysticks buttonTwoName) {
	buttonToggle(buttonOneName, buttonTwoName);
}
